config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :users

  resource :user_confirmation, :only => [:show]

  root :to => "home#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :title, :location, :description
  validates_length_of :description, :minimum => 30, :allow_blank => false
  validates_length_of :title, :minimum => 10, :maximum =>30

  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, :minimum => 30, :allow_blank => false
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :email

  has_secure_password

  before_create :generate_token

  def generate_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.limit(3)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_confirmations_controller.rb
class UserConfirmationsController < ApplicationController
  def show
    user = User.find_by_confirmation_token(params[:token])

    if user.present?
      user.confirm!
      redirect_to user, :notice => I18n.t('users.confirmations.success')
    else
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      SignupMailer.confirm_email(@user).deliver
      redirect_to @user, :notice => "Cadastro criado com sucesso!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, :notice => "Cadastro atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :location, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first, :class => "error_message"
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>

<ul>
<% @rooms.each do |room| %>
  <li><%= link_to room.complete_name, room %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
   <link href='http://fonts.googleapis.com/css?family=Pacifico'
rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div id="header-wrap">
      <h1><%= link_to "colcho.net", root_path %> </h1>
      <nav>
        <ul>
          <li><%= link_to t("layout.rooms"), rooms_path %> </li>
          <li><%= link_to t("layout.signup"), new_user_path %></li>
        </ul> 
      </nav>
    </div>
  </header>

  <div id="content">
    <% if notice.present? %>
      <p id="notice"><%= notice %> </p>
    <% end %>

    <% if alert.present? %>
      <p id="alert"> <%= alert %>
    <% end %>


    <%= yield %>
  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<% if @room.errors.any? %>
  <div id="error_explanation">
    Há erros no formulário, por favor verifique!
  </div>
<% end %>

<%= form_for(@room) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.location %></td>
        <td><%= room.description %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to t("links.back"), rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t ".title", :title => @room.title %></strong>
</p>

<p>
  <%= t ".location", :location => @room.location %>
</p>

<p>
  <%= t ".description", :description => @room.description %>
</p>

<%= link_to t(".edit"), edit_room_path(@room) %> |
<%= link_to t("links.back"), rooms_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <%= t "general.form_error" %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @user, :location %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
  </p>

  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to "Voltar", @user %>

app/views/users/index.html.erb
<h1>Lista de usuários:</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Localização</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.location %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Perfil', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>

app/views/users/show.html.erb
<h1><%= t ".title", :full_name => @user.full_name %></h1>

<ul>
  <li><%= t ".location", :location => @user.location %></li>
  <li><%= t ".bio", :bio => @user.bio %></li>
  <li><%= t ".email", :email => @user.email %> </li>
</ul>

<%= link_to t(".edit") , edit_user_path(@user) %>